name: Build TWRP

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y repo git curl python3

    - name: Init repo
      run: |
        mkdir twrp
        cd twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-8.1

    - name: Sync repo
      run: |
        cd twrp
        repo sync --depth=1

    - name: Add device tree
      run: |
        cd twrp
        mkdir -p device/samsung/j2corelte
        cp -r ../* device/samsung/j2corelte/

    - name: Build
      run: |
        cd twrp
        source build/envsetup.sh
        lunch omni_j2corelte-eng
        make recoveryimage
